<?php

use App\Dish;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dishes = [
            // Kebab Habdul
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab al Curry'),
                'name' => 'Kebab al Curry',
                'description' => 'salsa al curry, pomodoro, lattuga e kebab di pollo',
                'price' => 6,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab Harissa'),
                'name' => 'Kebab Harissa',
                'description' => 'salsa harissa, peperoni, radicchio e kebab di pollo',
                'price' => 6,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab Greco'),
                'name' => 'Kebab Greco',
                'description' => 'salsa greca, cipolla, lattuga, peperoni, kebab e patatine',
                'price' => 6.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab Habdul'),
                'name' => 'Kebab Habdul',
                'description' => 'salsa al curry, salsa allo yogurt, pomodoro, lattuga, cipolla croccante, patatine e kebab di pollo',
                'price' => 7,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab Firranzia'),
                'name' => 'Kebab Firranzia',
                'description' => 'salsa francese, cipolla, peperoni, radicchio, patatine e kebab di pollo',
                'price' => 6,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 1,
                'slug' => Dish::getSlug('Kebab Mediterraneo'),
                'name' => 'Kebab Mediterraneo',
                'description' => 'salsa mediterranea, lattuga, pomodoro, cipolla e kebab di pollo',
                'price' => 8.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            // Pizzeria da Ciro
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Pizza Margerita'),
                'name' => 'Pizza Margerita',
                'description' => 'pomodoro san Marzano, mozzarella di bufala, basilico, olio evo',
                'price' => 6.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/margherita.webp'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Quattro Formaggi'),
                'name' => 'Quattro Formaggi',
                'description' => 'fior di latte campano, emmental, gorgonzola, pecorino sardo e olio evo',
                'price' => 8.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/quattroformaggi.webp'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Capricciosa'),
                'name' => 'Capricciosa',
                'description' => 'pomodoro san marzano, fior di latte campano, prosciutto cotto, funghi champignon, carciofi, olive nere e olio evo',
                'price' => 8.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/capricciosa.webp'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Quattro Stagioni'),
                'name' => 'Quattro Stagioni',
                'description' => 'pomodoro san marzano, fior di latte campano, prosciutto cotto, salame napoli, funghi champignon, carciofi e olive nere',
                'price' => 8.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/quattrostagioni.webp'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Tonnarella'),
                'name' => 'Tonnarella',
                'description' => 'pomodoro san marzano, fior di latte campano, filetti di tonno, cipolla rossa, basilico e olio evo',
                'price' => 8.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/tonnarella.jpg'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Salsiccia e Friarielli'),
                'name' => 'Salsiccia e Friarielli',
                'description' => 'fior di latte campano, provola affumicata, polpettine di salsiccia, friarielli napoletani e olio evo',
                'price' => 9.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/salsiccisafriarielli.jpeg'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Pistacchiosa'),
                'name' => 'Pistacchiosa',
                'description' => 'fior di latte campano, mortadella, burrata di bufala, pesto e granella di pistacchio',
                'price' => 10.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/pistacchiosa.jpeg'
            ],
            [
                'user_id' => 2,
                'slug' => Dish::getSlug('Pizza Fritta'),
                'name' => 'Pizza Fritta',
                'description' => 'gusti precedenti',
                'price' => 7.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
                'uploaded_img' => 'img/pizzafritta.webp'
            ],
            // Sushi Zen
            [
                'user_id' => 3,
                'slug' => Dish::getSlug('Shashimi Misto'),
                'name' => 'Shashimi Misto',
                'description' => '12 pezzi di tonno, salmone, spada e ricciola',
                'price' => 24.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 3,
                'slug' => Dish::getSlug('Nigiri Misto'),
                'name' => 'Nigiri Misto',
                'description' => '12 pezzi di tonno, salmone, spada e spigola',
                'price' => 20.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 3,
                'slug' => Dish::getSlug('Temaki Misto'),
                'name' => 'Temaki Misto',
                'description' => '2 temaki di tonno e 2 temaki di salmone',
                'price' => 18.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 3,
                'slug' => Dish::getSlug('Tempura Mista'),
                'name' => 'Tempura Mista',
                'description' => 'tempura mista di calmari e gamberi',
                'price' => 25.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 3,
                'slug' => Dish::getSlug('Tempura Mista di Verdure'),
                'name' => 'Tempura Mista di Verdure',
                'description' => 'tempura mista di verdure',
                'price' => 14.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            // Poke
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Spicy Tuna'),
                'name' => 'Spicy Tuna',
                'description' => 'riso bianco, tonno, goma wakame, cavolo rosso, carote, cetrioli, salsa ponzu, salsa spicy, peanuts, jalapeño, cipolla croccante, tobiko, sesamo',
                'price' => 10.90,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Roadt Beef'),
                'name' => 'Roadt Beef',
                'description' => 'riso integrale, roast beef all\'ingelse, pomodorini, avocado, germogli di soia, feta, aromatic gigner oil, house tartar, mandorle, sesamo',
                'price' => 10.90,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Vegan'),
                'name' => 'Vegan',
                'description' => 'quinoa, tofu grigliato bio, ceci, carote, avocado, salsa teriyaki, patata dolce croccante, sesamo',
                'price' => 10.90,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Sunny Salmon'),
                'name' => 'Sunny Salmon',
                'description' => 'riso bianco, juicy salmon, avocado, edamame, cavolo rosso, salsa speciale, crema di avocado, sesamo',
                'price' => 9.90,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Chicken'),
                'name' => 'Chicken',
                'description' => 'riso bianco, pollo teriyaki e zenzero, zucchine, pomodorini, cavolo rosso, salsa teriyaki, salsa spicy, mayo, cipollotto, mandorle, sesamo',
                'price' => 10.90,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Acai House Bowl'),
                'name' => 'Acai House Bowl',
                'description' => 'Acai, Banana, Lamponi, Mandorla, Gocce di Cioccolato, Nut Butter',
                'price' => 7.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Tropical Bowl'),
                'name' => 'Tropical Bowl',
                'description' => 'Acai, Fragole, Ananas, Granola, Miele',
                'price' => 7.50,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Mango e Lime'),
                'name' => 'Mango e Lime',
                'description' => 'mano e lime',
                'price' => 4.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 4,
                'slug' => Dish::getSlug('Ananas'),
                'name' => 'Ananas',
                'description' => 'Ananas',
                'price' => 3.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            // grill e pasta
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Rigatoni all\'Amatriciana'),
                'name' => 'Rigatoni all\'Amatriciana',
                'description' => 'rigatoni all\'amatriciana',
                'price' => 11.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Spaghetti alla Carbonara'),
                'name' => 'Spaghetti alla Carbonara',
                'description' => 'spaghetti alla carbonara',
                'price' => 12.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Penne al Pesto Genovese'),
                'name' => 'Penne al Pesto Genovese',
                'description' => 'penne al pesto genovese',
                'price' => 9.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Lasagne al Ragu'),
                'name' => 'Lasagne al Ragu',
                'description' => 'lasagne al ragu',
                'price' => 12.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Mezzemaniche Cacio e Pepe'),
                'name' => 'Mezzemaniche Cacio e Pepe',
                'description' => 'mezzemaniche cacio e pepe',
                'price' => 10.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Filetto al Pepe Verde'),
                'name' => 'Filetto al Pepe Verde',
                'description' => 'fieltto al pepe verde',
                'price' => 25.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Bistecca alla Fiorentina'),
                'name' => 'Bistecca alla Fiorentina',
                'description' => 'bistecca alla fiorentina, prezzo al Kg',
                'price' => 38.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Contro Filetto alla Griglia'),
                'name' => 'Contro Filetto alla Griglia',
                'description' => 'contro filetto alla griglia',
                'price' => 18.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Grigliata Mista'),
                'name' => 'Grigliata Mista',
                'description' => 'grigliata mista di salsiccia, fesa di vitello e cipollata',
                'price' => 18.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
            [
                'user_id' => 5,
                'slug' => Dish::getSlug('Patate al Forno'),
                'name' => 'Patate al Forno',
                'description' => 'patate al forno',
                'price' => 8.00,
                'available' => rand(0, 1),
                'is_visible' => rand(0, 1),
            ],
        ];

        foreach ($dishes as $dish) {
            $dish = Dish::create($dish);
        }
    }
}